/* Generated by bdf_to_u8g2.py */

#ifndef INCLUDED_EVERYDAY_U8G2_FONTS_H
#define INCLUDED_EVERYDAY_U8G2_FONTS_H

#include <stdint.h>
#include "u8g2.h"

#ifdef __cplusplus
extern "C" {
#endif

extern const uint8_t everyday_ample_u8g2_font[];
extern const uint8_t everyday_ample_black_u8g2_font[];
extern const uint8_t everyday_ample_black_original_u8g2_font[];
extern const uint8_t everyday_ample_blocky_u8g2_font[];
extern const uint8_t everyday_ample_blocky_black_u8g2_font[];
extern const uint8_t everyday_ample_blocky_bold_u8g2_font[];
extern const uint8_t everyday_ample_bold_u8g2_font[];
extern const uint8_t everyday_ample_bold_original_u8g2_font[];
extern const uint8_t everyday_ample_original_u8g2_font[];
extern const uint8_t everyday_slight_u8g2_font[];
extern const uint8_t everyday_slight_black_u8g2_font[];
extern const uint8_t everyday_slight_black_original_u8g2_font[];
extern const uint8_t everyday_slight_blocky_u8g2_font[];
extern const uint8_t everyday_slight_blocky_black_u8g2_font[];
extern const uint8_t everyday_slight_blocky_bold_u8g2_font[];
extern const uint8_t everyday_slight_bold_u8g2_font[];
extern const uint8_t everyday_slight_bold_original_u8g2_font[];
extern const uint8_t everyday_slight_original_u8g2_font[];
extern const uint8_t everyday_standard_u8g2_font[];
extern const uint8_t everyday_standard_black_u8g2_font[];
extern const uint8_t everyday_standard_black_original_u8g2_font[];
extern const uint8_t everyday_standard_blocky_u8g2_font[];
extern const uint8_t everyday_standard_blocky_black_u8g2_font[];
extern const uint8_t everyday_standard_blocky_bold_u8g2_font[];
extern const uint8_t everyday_standard_bold_u8g2_font[];
extern const uint8_t everyday_standard_bold_original_u8g2_font[];
extern const uint8_t everyday_standard_original_u8g2_font[];
extern const uint8_t everyday_tiny_u8g2_font[];
extern const uint8_t everyday_tiny_black_u8g2_font[];
extern const uint8_t everyday_tiny_black_original_u8g2_font[];
extern const uint8_t everyday_tiny_blocky_u8g2_font[];
extern const uint8_t everyday_tiny_blocky_black_u8g2_font[];
extern const uint8_t everyday_tiny_blocky_bold_u8g2_font[];
extern const uint8_t everyday_tiny_bold_u8g2_font[];
extern const uint8_t everyday_tiny_bold_original_u8g2_font[];
extern const uint8_t everyday_tiny_original_u8g2_font[];
extern const uint8_t everyday_typical_u8g2_font[];
extern const uint8_t everyday_typical_black_u8g2_font[];
extern const uint8_t everyday_typical_black_original_u8g2_font[];
extern const uint8_t everyday_typical_bold_u8g2_font[];
extern const uint8_t everyday_typical_bold_original_u8g2_font[];
extern const uint8_t everyday_typical_original_u8g2_font[];
extern const uint8_t everyday_vast_u8g2_font[];
extern const uint8_t everyday_vast_black_u8g2_font[];
extern const uint8_t everyday_vast_black_original_u8g2_font[];
extern const uint8_t everyday_vast_blocky_u8g2_font[];
extern const uint8_t everyday_vast_blocky_black_u8g2_font[];
extern const uint8_t everyday_vast_blocky_bold_u8g2_font[];
extern const uint8_t everyday_vast_bold_u8g2_font[];
extern const uint8_t everyday_vast_bold_original_u8g2_font[];
extern const uint8_t everyday_vast_original_u8g2_font[];

#ifdef __cplusplus
}  /* extern "C" */
#endif

struct everyday_entry { const char *name; const uint8_t *font; };
extern const struct everyday_entry all_everyday_fonts[];

#endif  /* INCLUDED_EVERYDAY_U8G2_FONTS_H */
