/* Generated by bdf_to_u8g2.py */

#ifndef INCLUDED_U8G2_VEXED_EVERYDAY_FONTS_H
#define INCLUDED_U8G2_VEXED_EVERYDAY_FONTS_H

#include <stdint.h>
#include "u8g2.h"

#ifdef __cplusplus
extern "C" {
#endif

extern const uint8_t everyday_ample_font[];
extern const uint8_t everyday_ample_black_font[];
extern const uint8_t everyday_ample_black_original_font[];
extern const uint8_t everyday_ample_blocky_font[];
extern const uint8_t everyday_ample_blocky_black_font[];
extern const uint8_t everyday_ample_blocky_bold_font[];
extern const uint8_t everyday_ample_bold_font[];
extern const uint8_t everyday_ample_bold_original_font[];
extern const uint8_t everyday_ample_original_font[];
extern const uint8_t everyday_slight_font[];
extern const uint8_t everyday_slight_black_font[];
extern const uint8_t everyday_slight_black_original_font[];
extern const uint8_t everyday_slight_blocky_font[];
extern const uint8_t everyday_slight_blocky_black_font[];
extern const uint8_t everyday_slight_blocky_bold_font[];
extern const uint8_t everyday_slight_bold_font[];
extern const uint8_t everyday_slight_bold_original_font[];
extern const uint8_t everyday_slight_original_font[];
extern const uint8_t everyday_standard_font[];
extern const uint8_t everyday_standard_black_font[];
extern const uint8_t everyday_standard_black_original_font[];
extern const uint8_t everyday_standard_blocky_font[];
extern const uint8_t everyday_standard_blocky_black_font[];
extern const uint8_t everyday_standard_blocky_bold_font[];
extern const uint8_t everyday_standard_bold_font[];
extern const uint8_t everyday_standard_bold_original_font[];
extern const uint8_t everyday_standard_original_font[];
extern const uint8_t everyday_tiny_font[];
extern const uint8_t everyday_tiny_black_font[];
extern const uint8_t everyday_tiny_black_original_font[];
extern const uint8_t everyday_tiny_blocky_font[];
extern const uint8_t everyday_tiny_blocky_black_font[];
extern const uint8_t everyday_tiny_blocky_bold_font[];
extern const uint8_t everyday_tiny_bold_font[];
extern const uint8_t everyday_tiny_bold_original_font[];
extern const uint8_t everyday_tiny_original_font[];
extern const uint8_t everyday_typical_font[];
extern const uint8_t everyday_typical_black_font[];
extern const uint8_t everyday_typical_black_original_font[];
extern const uint8_t everyday_typical_bold_font[];
extern const uint8_t everyday_typical_bold_original_font[];
extern const uint8_t everyday_typical_original_font[];
extern const uint8_t everyday_vast_font[];
extern const uint8_t everyday_vast_black_font[];
extern const uint8_t everyday_vast_black_original_font[];
extern const uint8_t everyday_vast_blocky_font[];
extern const uint8_t everyday_vast_blocky_black_font[];
extern const uint8_t everyday_vast_blocky_bold_font[];
extern const uint8_t everyday_vast_bold_font[];
extern const uint8_t everyday_vast_bold_original_font[];
extern const uint8_t everyday_vast_original_font[];

#ifdef __cplusplus
}  /* extern "C" */
#endif

struct everyday_entry { const char *name; const uint8_t *font; };
extern const struct everyday_entry all_everyday_fonts[];

#endif  /* INCLUDED_U8G2_VEXED_EVERYDAY_FONTS_H */
